### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by caiyongqi** [kunwuz/DGTN#3]
Could you give me the preprocessed result of Diginetica? Thank you very much.

**Comment by kunwuz** [comment]
Hi, we've updated the code and readme. Now the preprocessed result can be generated with codes in 'preprocess/'.

**Comment by caiyongqi** [comment]
> Hi, we've updated the code and readme. Now the preprocessed result can be generated with codes in 'preprocess/'.

Thank you very much!
