### ISSUE TITLE
Error ocurred when running neighborhood_retrieval.py

### ISSUE THREAD

**Issue by ZaraYi** [kunwuz/DGTN#4]
Hi,  I follow the usage in the readme and an error occurred when I run neighborhood_retrieval.py using the “Diginetica” dataset.
The console shows that ：
     File "..\DGTN-master\neigh_retrieval\knn.py", line 58, in find_sess
        sess_index += item_sess_map[item]
    KeyError: 31938

I think the error is resulted from the function _get_item_sess_map_  in knn.py line 19:
items = np.unique(sess[:-1]) 
because the item_id:31938 may be the last click item in the session, and  it is not the recorded in the  _item_sess_map_
I wonder if it is reasonable to change this line into "items = np.unique(sess) " to solve the problem?

looking forward to u reply, thank u!

**Comment by kunwuz** [comment]
Hi,

Thanks for your interest in this implementation. I'm not totally sure whether I remember it correctly. The last clicks should only appear as labels, so we can't do KNN operations on them. We didn't encounter this issue in the previous experiments, so there might be some subtle difference in the dataset or the preprocessing. 

However, I think your suggestion is also reasonable, so please feel free to change it.

For the KNN part, we majorly refer to that in [this implementation](https://www.dropbox.com/sh/dbzmtq4zhzbj5o9/AAB6IzeGn2xTm67-5bpbsQDca/Source-Code?dl=0&subfolder_nav_tracking=1). It might help to provide more information about the neighbor retrieval part.

**Comment by ZaraYi** [comment]
Thank u so much！

**Comment by kunwuz** [comment]
I've updated the repo according to your suggestion in our emails (cikm16_org_prepro.py). Thanks for your time!
