### ISSUE TITLE
experiment

### ISSUE THREAD

**Issue by w2f666** [kunwuz/DGTN#5]
Hi,
Under the convolution fusion function, when running the program with different neighborhood files, the experimental results did not change, but when running under the max function, the results changed but did not reach the results in your paper.

Is the neighborhood data generated by me wrong? Looking forward to your reply . Thank you very much!

**Comment by wanglunkang** [comment]
Hi,
are you finally get the results in the paper?

**Comment by w2f666** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by w2f666** [comment]
Hi !
I haven't got the results in the diginetica dataset yet.

**Comment by kunwuz** [comment]
Hi, if possible, could you please illustrate your experimental setting?

**Comment by w2f666** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
