### ISSUE TITLE
experiment

### ISSUE THREAD

**Issue by w2f666** [kunwuz/DGTN#6]
hi.
I cannot achieve the results in your paper using  Diginetica data set.  Are there any other parameters that need to be set?

**Comment by wanglunkang** [comment]
hi.
can you get the result by the data of Yoochoose1/64?

**Comment by kunwuz** [comment]
Hi, if possible, could you please illustrate your experimental setting?

**Comment by w2f666** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
